@echo off & Title TS2 Ripper & color 0B

echo "  _______ _____ ___    _____  _                       "
echo " |__   __/ ____|__ \  |  __ \(_)                      "
echo "    | | | (___    ) | | |__) |_ _ __  _ __   ___ _ __ "
echo "    | |  \___ \  / /  |  _  /| | '_ \| '_ \ / _ \ '__|"
echo "    | |  ____) |/ /_  | | \ \| | |_) | |_) |  __/ |   "
echo "    |_| |_____/|____| |_|  \_\_| .__/| .__/ \___|_|   "
echo "                               | |   | |              "
echo "                               |_|   |_|              "
echo.
echo TS2 Ripper v0.3
echo Deletes Homefront: The Revolution game files that are not required to play Timesplitters 2
echo Script By Scotch
echo https://discord.gg/yBMxG7yT
echo.
echo.

timeout /t 4 >nul

echo Enter the path to Homefront: The Revolution game folder (no trailing slash)
echo Example: D:\Steam\steamapps\common\Homefront_The_Revolution
echo.
set /p gamepath=Enter Path to Homefront_The_Revolution:%=%
if NOT "%gamepath%"=="" GOTO pathcheck
echo Did not get game path. Hit ENTER to exit.
pause
exit /b 1

:pathcheck
	IF EXIST %gamepath%\Bin64\Homefront2_Release.exe GOTO do_rip
	echo Invalid game path. Please try again.
	pause
	exit /b 1

:do_rip
	echo Ripping files
	
	mkdir "%gamepath%\ripped\gamehf2\_activitycache" > nul 2> nul
	mkdir "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	mkdir "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	mkdir "%gamepath%\ripped\localization" > nul 2> nul
	
	move "%gamepath%\gamehf2\_activitycache\*" "%gamepath%\ripped\gamehf2\_activitycache" > nul 2> nul
	
	move "%gamepath%\gamehf2\animations.pak" "%gamepath%\ripped\gamehf2" > nul 2> nul
	move "%gamepath%\gamehf2\core_patch_*" "%gamepath%\ripped\gamehf2" > nul 2> nul
	move "%gamepath%\gamehf2\music.pak" "%gamepath%\ripped\gamehf2" > nul 2> nul
	move "%gamepath%\gamehf2\sounds.pak" "%gamepath%\ripped\gamehf2" > nul 2> nul
	
	move "%gamepath%\localization\*" "%gamepath%\ripped\localization" > nul 2> nul
	move "%gamepath%\ripped\localization\english_xml.pak" "%gamepath%\localization" > nul 2> nul
	
	move "%gamepath%\gamehf2\content\content_10_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_10_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_100_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1000_static_patch_5.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_10000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_100000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_100000008_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_100000018_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1000040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1000080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1001000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1008000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1008040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_104_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_108000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_12_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_14_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1400000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_14000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_14000040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_14004000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_15000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_15008000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_15008040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_174_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_178_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_17c_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_18_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_18_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1800000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1c00000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1c80c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1fc_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_20_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_200_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_200_static_patch.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_200_static_patch_2.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_200_static_patch_3.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_200_static_patch_4.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_200_static_patch_5.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_200_static_patch_6.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_20000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_24_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2400000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_24010bdc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2404000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_242e06f1e_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_249e0c0be_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_249e0e900_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_24bc0efc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_24be0c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_24be4c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_24dc0c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_25fe4c0c2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_278_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_27be0c700_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2c00000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2c04000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2cfc0c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2cfe0c0c2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2dbe0c4c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2dbf4ff80_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2dbf4ff98_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2e3f07f02_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fb74ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fb74ffdb_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbc4c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbe4c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbe4cb42_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbe4cbc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbe4cbc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbe4cf42_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbe4dbc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbe4ffde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbe5cbc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbf4cb42_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbf4dfca_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbf4ffc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbf4ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbf4ffdb_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbf4ffde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbf4ffdf_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbf5ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbf5ffdb_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbf5ffde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbf5ffdf_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbf6ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbf6ffde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbf7ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbf7ffdf_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbfcffc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbfeffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fbffffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2ffefcac0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2fffeffdb_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2ffffffdf_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_30_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_34_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_36_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_3c_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_3e_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul1
	move "%gamepath%\gamehf2\content\content_40_static001.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_400_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_400000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40000080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4000080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40004000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_400080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40008000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4000c000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4008000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4008080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_400c000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4010b9c2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_404000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40400000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40404000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40404100_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_408000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40800000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40804000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40c00000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40c00080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40c04000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40c04080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40c04400_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40c08000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40c0c000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_41000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_41008000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_41800000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_41804000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_41c04000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_41c05000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_42000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_42008000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_42208000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_42400000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_42404000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_42600000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_42800000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_42c04000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_42c04080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_42c0c000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_42e06f16_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_42e06f1e_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_44_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_44000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_440000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4400c000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_441000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_444000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_449e6c042_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_44b209f9e_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_44cc6c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_46400000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_46ee0ccc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_48_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4800000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_48000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_48c00000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_48c04000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_48c0c000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49008000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49009000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49408040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49800040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49804040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4990c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c00000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c04000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c04040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c04080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c08040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c08080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c0c000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c0c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c0c080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c0c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c0e900_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c4c000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c4c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c5c0d1_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c5c0d9_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c6c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c6e140_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49d0c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4ac04000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4ac0c000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4b209b96_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4b209b9e_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4b209f9e_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bc04000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bc04040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bc040c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bc0c000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bc0c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bc0c080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bc0c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bc0c800_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bc0eac0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bc0ebc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bc6c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bc6c042_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bc6c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bcfc040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4be0c000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4be0c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4be4c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4c804000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4c804100_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4cc04000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4cc04100_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4cc0c000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4cc0c100_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4cc6c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4dc0c082_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4dc0c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4dc1c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4e_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4ebe4df9e_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4ec04000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4ec0c0c2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4fc0c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4fc6c002_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4fde6c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4fe6c6c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_50_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_50000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_5008000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_52404400_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_52404500_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_58_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_5bc0c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_60_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_60000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_6000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_60040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_60e0c880_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_62240000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_64_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_6400000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_64bf4c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_67be0c700_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_68040040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_69004000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_6b249b96_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_6bccc042_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_6bccc0c2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_6ee0ccc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_6fe0c8c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_70_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_70c0c080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_74_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_78_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_79404000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_7bc0c042_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_7bc0c700_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_7c_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_7fc6c8c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_80_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_80_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_800_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_800000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_80000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_80000040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8000040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8004000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8008000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_804000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_810_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_81240000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_83800800_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_83803800_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8400000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_850_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_87a_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_87c_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8800000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_89000040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8c00000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8c00002_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8c08040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8fbe4cb40_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8ffe6c1c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_90_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9000040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9000100_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9004000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9004040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9008000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9008040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9008080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9048000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9400000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9404040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_97c_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9800040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9804000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9c0c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9c0c080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9fc_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_a400080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_a400480_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_a7e_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_a84400c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_afbe4cbc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_afbe4dbc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_afbf4cb42_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_afbf7ffde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_b7e_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_bc_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_bfe_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c00000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c0000000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c0000080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c04000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c040c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c04480c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c2e08080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c30480c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c3c04800_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c3e04800_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c9008080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c9c0c00a_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c9c0c080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c9c0c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c9c6e140_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cac08242_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cbc0825a_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cbc0c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cbc0c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cbc0c800_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cbc4c01e_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cbc4c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cbc6c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cd810040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cdc0c082_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cdc1c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cde04040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cfc0c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cfc0c1c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cfc1c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cfcfc2c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_d2240058_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_d2248058_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_d40000c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dbc0c080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dbc5c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dbd0d0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dbe0c080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dbe0fcd6_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dbe0fcde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dbe4cbc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dbe5c0ca_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dbf4ff80_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dbf4ff98_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dbf4ffc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dfe_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dfe_static_patch.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dfe_static_patch_2.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dfe_static_patch_3.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dfe_static_patch_4.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dfe_static_patch_5.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_dfe_static_patch_6.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_e2e04096_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_e3e04e02_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_e3f07f02_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_e4bc0efc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_ebe0c496_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_ebe4cd96_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_ebe7c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_edbf4ff80_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_edbf4ff98_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbe4efde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf4ffc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efefc9c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_f4_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fb74ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fb74ffdb_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbc4c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbcfc0c1_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbdec6c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbe0cc40_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbe4c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbe4cb40_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbe4cb42_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbe4cbc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbe4cbc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbe4cf42_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbe4cfca_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbe4dbc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbe4fbc6_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbe4fbde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbe4ffd6_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbe5cbc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbe5dfc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbefc4c1_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4cb40_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4cb42_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4cbc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4cf42_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4cfca_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4dfc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4dfca_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4dfdb_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4efca_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4ffc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4ffc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4ffca_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4ffd6_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4ffdb_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4ffde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf4ffdf_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf5cb42_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf5cfc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf5ffca_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf5ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf5ffdb_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf5ffde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf6ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf6ffde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf7ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbf7ffdf_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbffcbde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbffffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbffffdb_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fc_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fdc6c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fde6c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fee0c880_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fee0c980_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_ffc_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_ffe7ccc0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_ffefcec0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fff_static_patch.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fff_static_patch_3.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fff_static_patch_4.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fff_static_patch_5.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fff4ffde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fff7ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fffeffdb_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_ffffffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_ffffffdf_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_10_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_100_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_1000_static_patch_5.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_104_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_14_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_174_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_178_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_17c_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_18_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_1fc_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_20_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_200_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_200_static_patch.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_200_static_patch_2.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_200_static_patch_3.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_200_static_patch_4.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_200_static_patch_5.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_24_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_278_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_30_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_3c_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_4_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_40_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_400_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_44_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_48_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_4e_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_50_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_58_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_60_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_64_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_70_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_74_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_78_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_8_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_80_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_800_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_810_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_850_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_87a_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_87c_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_90_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_97c_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_9fc_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_a7e_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_b7e_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_bc_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_bfe_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_dfe_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_f4_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_fc_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_ffc_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_fff_static_patch.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_fff_static_patch_2.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_fff_static_patch_3.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_fff_static_patch_4.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_fff_static_patch_5.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1000002_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_10040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1800002_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1a_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1e_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_1_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_24bccc0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2cde1c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2ebcfc0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40000002_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4002_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_42884080_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_43c6c042_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_449c04002_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_44dc0c082_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_48010040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_49c1c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4accc000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bc6c05b_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4bc7c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4dbdfc0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_4fbc1c0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_67fe7c7c2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_6be0c49e_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_6efefc9c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_6fdedc0c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8000002_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_800002_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_80000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8002_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8080000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_85bc0c042_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_89010040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8c0001a_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8cbc0c002_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_8cfcef9c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9008002_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9408002_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_9810040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_ae3f07f02_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_afbe4cb42_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_afbe4cbc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_afbe4cf42_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_afbe6cbca_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_afbf4cfc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_afbf4ffde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c0000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c040001e_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c090e8000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c49c6c042_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c4b209f9e_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c4fc0c0c2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c8cc4000_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_c9c1c040_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cbe0825a_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cd9dec082_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cdbe0fcde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_cfc140c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_e2e0409e_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_e38fc0c1_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_e4010bdc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_e42e06f1e_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_ebe4cd9e_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efb74ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efb74ffdb_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbe4cb42_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbe4cbc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbe4dfc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbe4efca_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbe4effe_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbe5cbc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf4cfc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf4ffc2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf4ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf4ffdb_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf4ffde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf4ffdf_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf5ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf5ffdb_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf5ffde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf5ffdf_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf6ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf6ffde_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf7c4c0_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf7ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbf7ffdf_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efbffffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_effeccc40_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efff7ffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_efffeffdb_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_effffffda_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_effffffdf_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_fbc1c0c2_cache.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_200_static_patch_6.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_34_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_7c_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_fff_static002.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_fff_static_patch_6.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_40_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_dfe_static_patch.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_dfe_static_patch_2.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_dfe_static_patch_3.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_dfe_static_patch_4.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_dfe_static_patch_5.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_dfe_static_patch_6.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_fff_static.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\content\content_hi_fff_static001.pak" "%gamepath%\ripped\gamehf2\content" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_1000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_10000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_100000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_1000000000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_100fff880_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_100fffc80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_100fffc84_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_1047f6400_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_110000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_12000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_1264000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_138bffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_138fffc80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_138fffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_138fffc84_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_138fffc85_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_139fffc80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_13abffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_13cbffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_13efffc85_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_140000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_146000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_152000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_17bfffc85_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_17dfffc8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_17dffffef_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_17feffc8d_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_17fffec00_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_17ffffc84_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_17ffffc8d_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_17ffffc8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_17ffffcc1_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_17ffffccd_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_17ffffd8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_17ffffdcf_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_17fffffef_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_1bafffdff_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_1bdfffccd_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_1fff9e0_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_200_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_2000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_20000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_200000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_20204000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_20376080_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_204000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_204080_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_20b56280_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_20f769c0_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_224800_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_23760c0_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_284080_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_29bfe01f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_3400_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_366000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_37e280_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_38bfec80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_38bffc80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_38bffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_38ffec80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_38fffc80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_38fffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_38fffc84_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_38fffc85_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_38fffd81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_39bfec80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_39fffc80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_3abffc80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_3abffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_3afffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_3afffc85_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_3bfffc85_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_3cbffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_3ebffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_3efffc85_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_3f6005_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_3f79c0_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_3ffffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_4_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_4000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_40000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_400000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_40200_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_42000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_4376080_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_438bfec80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_438bffc80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_438ffec80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_45880_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_461f76000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_49d340b_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_4c0000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_4e2880_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_4ffe00b_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_538fffc80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_538fffc84_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_538fffc85_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_539fffc80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_53efffc85_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_57ffffc8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_73afffdff_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_73bfffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_73d7d200d_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_73fbffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_77feffc8d_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_77fffec00_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_77ffffc84_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_77ffffc85_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_77ffffc8d_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_77ffffc8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_77ffffd8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_77ffffdcf_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_77ffffe8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_77fffffef_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_78ffe083_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_79fffc83_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_79fffc8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7bfffc85_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7dfffc8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7fdfffc8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7feffc8d_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7fffec00_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7ffffc85_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7ffffc8b_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7ffffc8d_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7ffffc8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7ffffccd_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7ffffd8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7ffffdcf_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7ffffded_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7ffffe8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7fffffcd_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_7fffffef_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_8_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_800_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_8000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_80000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_800000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_80000000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_800000000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_8007ff000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_80080_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_801264000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_802000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_9bfe01b_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_b769e0_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_b7e280_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_bf6880_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_c_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_c0c00_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_c61f76000_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_ee0880_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_f56081_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_f7fffec00_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_f7ffffc84_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_ffe9a0_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_fff880_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_fff9a0_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_fffc80_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_fffc84_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_ffffffcd_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_10_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_200b72001_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_20_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_400bf6001_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_40b769e0_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_440c0_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_49d340f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_538bffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_538fffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_538fffd81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_53cbffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_738bffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_738fffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_884bf609f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_c0_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_d38bffc81_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_d7efffc8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_d7ffffc8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_f769c0_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_f7feffc8d_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_f7feffc8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_f7ffffc8d_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_f7ffffc8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_f7ffffcc1_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_f7ffffcc5_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_f7ffffd8f_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_f7ffffdcf_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_f7fffffad_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	move "%gamepath%\gamehf2\_levelcache\bundle_f7fffffef_cache.pak" "%gamepath%\ripped\gamehf2\_levelcache" > nul 2> nul
	
	echo Done!
	echo All non-essential files moved to this folder:
	echo "%gamepath%\ripped"
	echo To undo this mod, move everything in "ripped" back into your Homefront folder.
	echo Once you've tested the game, you can delete the ripped files.
	echo.
	echo Press ENTER to exit.
	pause
	exit /b 0